-- ============================================================================
-- SEED DANH MỤC CÔNG VIỆC CHUẨN — sinh tự động từ qlnb.xlsx (sheet Mảng công
-- việc / Công việc / Cán bộ). 444 đầu việc, 13 cán bộ.
-- Chạy sau 08-mang-cv-va-danh-muc-chuan.sql. Chạy lại an toàn (on conflict).
-- ============================================================================

-- Nhân sự mới: Huỳnh Thị Bắc (Khoán gọn) — mã CBNV tạm thời, CHƯA có tài khoản
-- đăng nhập (accounts) cho tới khi có mã CBNV thật.
insert into employees (ma_cbnv, ho_ten, chuc_danh, department_id, nhom_nghiep_vu, app_role, kpi_phu_luc, quan_ly_truc_tiep_id)
select 'TAMTHOI-BACHT', 'Huỳnh Thị Bắc', 'Khoán gọn (nhân viên hợp đồng khoán)', d.id, 'TCHC', 'canbo',
  'Chưa có phụ lục KPI riêng', (select id from employees where ma_cbnv = '00169422')
from departments d where d.ma_phong = 'QLNB'
on conflict (ma_cbnv) do nothing;

-- Phân công mảng cho từng cán bộ (1 người có thể thuộc nhiều mảng).
insert into employee_mang_cv (employee_id, mang_cv_id)
select e.id, m.id
from (values
  ('00157251', 1),
  ('00157251', 2),
  ('00157251', 3),
  ('00157251', 4),
  ('00157251', 5),
  ('00157251', 6),
  ('00157251', 7),
  ('00157251', 8),
  ('00169422', 1),
  ('00169422', 2),
  ('00169422', 3),
  ('00169422', 4),
  ('00169422', 5),
  ('00169422', 6),
  ('00169422', 7),
  ('00169422', 8),
  ('00157279', 1),
  ('00157279', 2),
  ('00157279', 3),
  ('00157279', 4),
  ('00157279', 5),
  ('00157279', 6),
  ('00157279', 7),
  ('00157279', 8),
  ('00157280', 1),
  ('00157280', 2),
  ('00157280', 3),
  ('00157280', 4),
  ('00157280', 5),
  ('00157280', 6),
  ('00157280', 7),
  ('00157280', 8),
  ('00146999', 1),
  ('00146999', 2),
  ('00146999', 8),
  ('00157267', 4),
  ('00157267', 8),
  ('00157275', 2),
  ('00157275', 3),
  ('00157275', 4),
  ('00157275', 7),
  ('00157275', 8),
  ('00183881', 1),
  ('00183881', 2),
  ('00183881', 3),
  ('00183881', 7),
  ('00183881', 8),
  ('00157761', 2),
  ('00157761', 8),
  ('00157764', 2),
  ('00157764', 8),
  ('00157765', 2),
  ('00157765', 8),
  ('00157760', 2),
  ('00157760', 8),
  ('TAMTHOI-BACHT', 2),
  ('TAMTHOI-BACHT', 6),
  ('TAMTHOI-BACHT', 8)
) as v(ma_cbnv, ma_mang)
join employees e on e.ma_cbnv = v.ma_cbnv
join mang_cv m on m.ma_mang = v.ma_mang
on conflict (employee_id, mang_cv_id) do nothing;

-- Danh mục công việc chuẩn — điểm riêng từng cấp, NULL = cấp đó không tham gia.
insert into job_catalog (ma_cv, ten_cong_viec, mang_cv_id, diem_can_bo, diem_kiem_soat, diem_truong_phong, diem_pgd, diem_gd)
select v.ma_cv, v.ten_cong_viec, m.id, v.diem_can_bo, v.diem_kiem_soat, v.diem_truong_phong, v.diem_pgd, v.diem_gd
from (values
  ('KHTH-001','KHTH1 - Phối hợp với các Phòng XDKHKD của CN, gửi HSC đúng thời hạn kỳ năm',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-002','KHTH2 - Phối hợp với các Phòng XDKHKD của CN, gửi HSC đúng thời hạn kỳ Quý',3,80.0::numeric,80.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-003','KHTH3 - Giao KHKD cho các phòng nghiệp vụ theo đúng tiến độ kỳ Năm',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-004','KHTH4 - Giao KHKD cho các phòng nghiệp vụ theo đúng tiến độ kỳ Quý',3,70.0::numeric,70.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-005','KHTH5 - Tham mưu đề xuất giải pháp điều hành thực hiện NVKD - Rà soát, đ/c KHKD của CN gửi TSC',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-006','KHTH6 - Tham mưu đề xuất giải pháp điều hành thực hiện NVKD - Rà soát, đ/c KHKD các Phòng tại CN',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-007','KHTH7 - Đầu mối/Thực hiện XD tiêu chí, ban hành TB HD xét HTNV tập thể và cá nhân tại CN',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-008','KHTH8 - Thực hiện xét HTNV tập thể và cá nhân kỳ năm',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-009','KHTH9 - Thực hiện xét HTNV tập thể và cá nhân kỳ quý',3,80.0::numeric,80.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-010','KHTH10 - Đầu mối/ Thực hiện chấm điểm công tác đánh giá HTNV, xếp hạng CN kỳ Năm',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-011','KHTH11 - Đầu mối/ Thực hiện công tác đánh giá HTNV, xếp hạng CN kỳ Quý',3,80.0::numeric,80.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-012','KHTH12 - Phối hợp trong công tác xếp hạng PGD',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-013','KHTH13 - Báo cáo kết quả HĐKD Chi nhánh hàng ngày',3,10.0::numeric,0.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-014','KHTH14 - Báo cáo kết quả HĐKD Chi nhánh hàng Tháng',3,50.0::numeric,0.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-015','KHTH15 - Báo cáo kết quả HĐKD Chi nhánh hàng Quý/6 tháng/Năm',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-016','KHTH16 - Báo cáo tình hình hoạt động của các phòng nghiệp vụ hàng tháng',3,50.0::numeric,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-017','KHTH17 - Thu thập thông tin địa bàn, chính sách giá phí của đối thủ cạnh tranh định kỳ 6 tháng/lần',3,50.0::numeric,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-018','KHTH18 - Báo cáo thống kê thông tư 11',3,10.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-019','KHTH19 - Báo cáo đột xuất theo yêu cầu của Lãnh đạo Chi nhánh, Trụ sở chính',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-020','KHTH20 - Báo cáo ngoại ngành',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-021','KHTH21 - Đầu mối/ TH cập nhật, theo dõi, triển khai các SP HĐV DC&#59; LS HĐV&#59; điều hành vốn',3,40.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-022','KHTH22 - Đầu mối/phối hợp thực hiện/ Thực hiện xây dựng, đề xuất chính sách KH HĐV',3,100.0::numeric,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-023','KHTH23 - Kiểm soát/ Thực hiện cài đặt lãi suất HĐV dân cư tại Chi nhánh',3,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-024','KHTH24 - TB lãi suất cho vay KHDN, theo dõi các gói cho vay ưu đãi',3,20.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-025','KHTH25 - Quản lý trạng thái ngoại tệ của CN',3,50.0::numeric,30.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-026','KHTH27 - Kiểm soát giao dịch ngoại tệ, phái sinh của các Phòng và đối ứng với HSC',3,20.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-027','KHTH28 - Triển khai các công văn/sản phẩm liên quan đến nghiệp vụ KDNT',3,30.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-028','KHTH29 - Kiểm soát thông báo nguồn thanh toán',3,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-029','KHTH 30 - Phối hợp với các Phòng/CN TGYK xây dựng biểu phí DV&#59; Ban hành biểu phí DV tại CN',3,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-030','KHTH31 - Tổng hợp kiến nghị, đề xuất các CS phí DV, CSKH định kỳ hoặc đột xuất trình GĐ/Hội đồng DV',3,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-031','KHTH32 - Theo dõi cơ chế động lực của HSC',3,40.0::numeric,40.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-032','KHTH33 - Ban hành văn bản phát động thi đua tại Chi nhánh',3,30.0::numeric,30.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-033','KHTH34 - Thực hiện khen thưởng tới các phòng nghiệp vụ',3,30.0::numeric,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-034','KHTH35 - Theo dõi rà soát công tác gán AM RM của các phòng nghiệp vụ',3,20.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-001','CNTT40 - Thực hiện các công tác liên quan khác về duy trì, thiết lập hạ tầng phần cứng tại CN',5,8.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-002','CNTT41 - Quản trị hệ thống kiểm soát kết nối Internet tại CN',5,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-003','CNTT42 - Xây dựng hệ thống mạng/điện/điện thoại/camera phục vụ mở mới PGD',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-004','CNTT43 - Hướng dẫn, ĐT, hỗ trợ, KTGS việc thực hiện, tuân thủ các QĐ và QT của BIDV trong CNTT',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-005','CNTT44 - Tổ chức triển khai chính sách ATBM CNTT tới các bộ phận',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-006','CNTT45 - Lập báo cáo và đánh giá An toàn thông tin liên qua đến CNTT, báo cáo ISO liên quan đến CNTT',5,80.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-007','CNTT46 - Triển khai thiết bị CNTT PGD số tại CN',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-008','CNTT47 - Quản trị các thiết bị tại PGD số, quản lý phần mềm triển khai tại PGD số',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-009','CNTT48 - Hướng dẫn và hỗ trợ KH khi triển khai SPDV cho KHDN',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-001','HCVP1 - Lập kế hoạch mua sắm, trang bị TS, CCLĐ',2,10.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-010','CNTT49 - Khảo sát khách hàng mở kết nối với các đối tác (Thanh toán hóa đơn, Thu hộ…)',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-002','HCVP2 - Lập kế hoạch kiểm kê TS, CCLĐ',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-011','CNTT50 - Phối hợp với các đơn vị, BPQL ATM thực hiện cập nhật, bảo trì, khắc phục lỗi các máy ATM',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-003','HCVP3 - Lập kế hoạch thanh lý TS, CCLĐ',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-012','CNTT51 - Xây dựng chương trình hỗ trợ nghiệp vụ cho các phòng theo yêu cầu của BGĐ, các phòng',5,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-004','HCVP4 - Lập kế hoạch bảo trì, bảo dưỡng TS, CCLĐ',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-013','CNTT52 - Định kỳ tháng, quý lấy SL TSGD, HQ GD, hoạt động của các ĐV p/vụ chấm HTNV theo BSC và KPI',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-005','HCVP5 - Đề xuất sửa chữa TS, CCLĐ',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-014','CNTT53 - Kết xuất dữ liệu hỗ trợ nghiệp vụ cho các phòng khi có phát sinh',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-006','HCVP6 - Triển khai các thủ tục mua sắm TS, CCLĐ',2,8.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-015','CNTT54 - Cấu hình POS cho các Phòng để triển khai lắp đặt cho các ĐVCNT',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-007','HCVP7 - Triển khai các thủ tục kiểm kê TS, CCLĐ',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-016','CNTT55 - Quản trị và hỗ trợ máy tính kết nối Internet (truyền nhận file với NHNN, đối tác,…)',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-008','HCVP8 - Triển khai các thủ tục thanh lý TS, CCLĐ',2,8.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-017','CNTT56 - Tham gia phối hợp trong công tác kiểm tra nội bộ tại CN và đoàn kiểm tra ngoài, ISO.',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-009','HCVP9 - Triển khai các thủ tục sửa chữa TS, CCLĐ',2,8.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-018','CNTT57 - Tham mưu, ĐX với cấp có TQ về KH UDCNTT, vấn đề l/q đến CNTT và những VĐ cần kiến nghị...',5,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-010','HCVP10 - Triển khai các thủ tục bảo trì, bảo dưỡng TS, CCLĐ',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-011','HCVP11 - Theo dõi quản lý TS,CCLĐ, đảm bảo cân đối giữa sổ sách và thực tế',2,20.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-012','HCVP12 - Thực hiện các thủ tục giao nhận TS, CCLĐ đúng theo quy định',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-013','HCVP13 - Chủ động và phối hợp trong công tác đánh giá hiện trạng TS, CCLĐ, có BP xử lý sau đánh giá',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-014','HCVP14 - Thực hiện các báo cáo theo yêu cầu của lãnh đạo',2,20.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-015','HCVP15 - Thực hiện các thủ tục thanh toán các chi phí liên quan tới mua sắm, sửa chữa TS, CCLĐ',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-016','HCVP16 - Thực hiện các thủ tục thanh toán các chi phí liên quan tới thuê mua TS',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-017','HCVP17 - Thực hiện các thủ tục thanh toán các chi phí liên quan tới sử dụng dịch vụ phục vụ HĐKD',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-018','HCVP18 - Thực hiện tốt nhiệm vụ tại các Tổ mua sắm, nghiệm thu, tổ thẩm định theo QĐ của Giám đốc',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-019','HCVP19 - QL&SD TS, CCLĐ - Lưu hồ sơ theo quy định',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-020','HCVP20 - Có KH trong công tác đầu tư XDCB (sửa chữa, thiết kế, trang bị CSVC, nội ngoại thất...)',2,10.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-021','HCVP21 - Triển khai các thủ tục cải tạo, sửa chữa cơ sở vật chất',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-022','HCVP22 - Giám sát việc sửa chữa, trang bị nội ngoại thất theo KH/phát sinh được BLĐ phê duyệt',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-023','HCVP23 - Chủ động và p/hợp trong đánh giá hiện trạng CSVC tuân thủ nhận diện TH và có BP, ĐX sau đ/g',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-024','HCVP24 - Thực hiện các báo cáo theo yêu cầu của lãnh đạo',2,40.0::numeric,40.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-025','HCVP25 - Thực hiện tốt nhiệm vụ tại Ban quản lý công trình theo quyết định của Giám đốc',2,20.0::numeric,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-026','HCVP26 - SC, ĐT XD CSVC - Lưu hồ sơ theo quy định',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-027','HCVP27 - Lập kế hoạch mua sắm và sử dụng VPP, Ấn chỉ thường',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-028','HCVP28 - Thực hiện các thủ tục mua sắm VPP và AC thường theo KH/phát sinh được BLĐ phê duyệt',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-029','HCVP29 - Theo dõi và quản lý kho ấn chỉ đảm bảo cân đối giữa sổ sách và thực tế',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-030','HCVP30 - Thực hiện các thủ tục giao nhận đúng quy định và lưu đầy đủ hồ sơ liên quan',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-031','HCVP31 - Thực hiện thanh toán các chi phí liên quan tới VPP, Ấn chỉ thường',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-032','HCVP32 - Chủ động và phối hợp tốt trong công tác đánh giá hiệu quả sử dụng VPP và Ấn chỉ thường',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-033','HCVP33 - Thực hiện báo cáo và phối hợp báo cáo theo yêu cầu của lãnh đạo',2,20.0::numeric,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-034','HCVP34 - Thực hiện tốt nhiệm vụ khi tham gia Tổ mua sắm, tổ nghiệm thu, Tổ thẩm định theo QĐ của GĐ',2,10.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-035','HCVP35 - QL&SD VPP, AC thường - Lưu hồ sơ theo quy định',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-036','HCVP36 -Lập KH đối với các khoản chi tiêu hành chính, công tác LTKT, hội nghị, hội thảo',2,10.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-037','HCVP37 - Thực hiện các thủ tục tạm ứng và hoàn tạm ứng đúng quy định',2,10.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-019','CNTT6 - Phối hợp với phòng TCHC, KHTC trong việc xác định thiết bị cần thanh lý.',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-020','CNTT39 - Quản trị các máy khác phục vụ CV của riêng CN (máy chủ truyền nhận file, web nội bộ)',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-001','TCNS12 - Lập tờ trình đề xuất với Lãnh đạo về việc điều động, luân chuyển',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-002','TCNS14 - ĐĐLC-Cập nhật trên chương trình QLNS',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-038','HCVP38 - Thực hiện chi tiêu theo quy định',2,10.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-039','HCVP39 - Đầu mối/phối hợp TH công tác hậu cần, TC hội nghị, hội thảo, CT lễ tân',2,10.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-040','HCVP40 - P/hợp TH các bảng, biển, decal đảm bảo theo nhận diện thương hiệu',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-041','HCVP41 - Thực hiện các báo cáo theo yêu cầu',2,30.0::numeric,30.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-042','HCVP42 - Thanh quyết toán các khoản chi tiêu theo quy định',2,15.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-043','HCVP43 - LTKT&CTHC - Lưu hồ sơ theo quy định',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-044','HCVP44 - Có KH, PA đảm bảo AN, AT đối với người và TS của Chi nhánh và thực hiện các BC liên quan',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-045','HCVP45 - P/h CQ địa phương, đối tác về DV an ninh ĐBAT và công tác vận chuyển TSCG theo QĐ của BIDV',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-046','HCVP46 - Có kế hoạch, PA đảm bảo PCCC theo đúng QĐ về an toàn PCCC tại TSCN và các PGD.',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-047','HCVP47 - Triển khai công tác PCCC tại CN',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-048','HCVP48 - P/h với các phòng nghiệp vụ, các đ/vị chức năng về PCCC đảm bảo hồ sơ đầy đủ, đúng QĐ...',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-049','HCVP49 - Có kế hoạch thực hiện công tác Quốc phòng tuân thủ theo QĐ của nhà nước.',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-050','HCVP50 - Tổ chức/Phối hợp t/hiện công tác ANQP, dân quân tự vệ, quân nhân tại ĐV và các BC liên quan',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-051','HCVP51 - ANQP&PCCC - Lưu hồ sơ theo quy định',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-052','HCVP52 - Quản lý và sử dụng con dấu của cơ quan theo đúng quy định',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-053','HCVP53 - Đầu mối tiếp nhận VB đi, VB đến (bao gồm cả thư BL) và mở sổ theo dõi với các loại VB trên',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-054','HCVP54 - Thực hiện các thủ tục chuyển phát văn bản đến đúng nơi quy định',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-055','HCVP55 - Đầu mối tiếp nhận thư, CPN từ các đơn vị dịch vụ và chuyển đến đúng nơi theo yêu cầu',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-056','HCVP56 - Lưu hồ sơ, văn bản công tác văn thư theo quy định',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-057','HCVP57 - Tuân thủ việc điều động của lãnh đạo trong việc vận chuyển người và tài sản của đơn vị',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-058','HCVP58 - Thực hiện lái xe AT trong quá trình vận chuyển (ATGT, an toàn cho người và tài sản)',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-059','HCVP59 - Tuân thủ về QĐ quản lý và sử dụng TSLĐ của đơn vị (tiết kiệm, hiệu quả, đúng mục đích...)',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-060','HCVP60 - Thực hiện thanh toán các chi phí liên quan công tác vận chuyển',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-061','HCVP61 - Lưu hồ sơ công tác vận chuyển theo quy định',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-003','TCNS91 - Ban hành thông báo tới các phòng v/v đề xuất/bổ sung quy hoạch cán bộ',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-004','TCNS92 - Tổng hợp nhu cầu quy hoạch của các phòng, chuẩn bị tài liệu họp',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-005','TCNS93 - Tổ chức họp Hội nghị liên tịch thông qua danh sách tổng hợp quy hoạch',1,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-006','TCNS94 - Tổ chức họp và bỏ phiếu tại Hội nghị cán bộ',1,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-007','TCNS95 - Tổ chức họp Hội nghị liên tịch để thống nhất danh sách đề nghị quy hoạch',1,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-008','TCNS96 - Lập biên bản cuộc họp Hội nghị liên tịch ký các thành viên cuộc họp',1,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-009','TCNS97 - Lập hồ sơ quy hoạch gửi HO báo cáo hoặc xin ý kiến phê duyệt',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-010','TCNS98 - Thông báo/phổ biến kết quả quy hoạch',1,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-011','TCNS99 - Cập nhật trên chương trình QLNS',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-012','TCNS100 - Lưu hồ sơ quy hoạch',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-013','TCNS101 - Lập kế hoạch đào tạo, bồi dưỡng, luân chuyển đối với cán bộ được phê duyệt quy hoạch.',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-035','KHTH36 - CV phát sinh trong q/trình thực hiện hoặc theo y/c của LĐ phòng/CN - Độ phức tạp cao',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-036','KHTH37 - CV phát sinh trong q/trình thực hiện hoặc theo y/c của LĐ phòng/CN - Độ phức tạp TB',3,70.0::numeric,70.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-037','KHTH38 - CV phát sinh trong q/trình thực hiện hoặc theo y/c của LĐ phòng/CN - Độ phức tạp thấp',3,40.0::numeric,40.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHAC-001','2023-TCKT52-Mở khóa kho tiền theo phân công của Lãnh đạo',8,NULL::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-001','2023-TCKT53-Tham gia các Tổ kiểm tra nội bộ, Tổ công tác khác',4,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-002','2023-TCKT54-Xuất hóa đơn thủ công',4,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-003','2023-TCKT55-Tham gia công tác kiểm kê (ấn chỉ, tài sản đảm bảo, tài sản…)',4,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-004','2023-TCKT56-Công tác khác - Độ phức tạp rất cao',4,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-005','2023-TCKT57-Công tác khác - Độ phức tạp cao',4,80.0::numeric,80.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-006','2023-TCKT58-Công tác khác - Độ phức tạp TB',4,50.0::numeric,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-007','2023-TCKT59-Công tác khác - Độ phức tạp thấp',4,20.0::numeric,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-038','2023-KHTH1-Phối hợp với các Phòng XDKHKD của CN, gửi HSC đúng thời hạn kỳ năm',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-039','2023-KHTH2-Phối hợp với các Phòng XDKHKD của CN, gửi HSC đúng thời hạn kỳ Quý',3,80.0::numeric,80.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-040','2023-KHTH3-Giao KHKD cho các phòng nghiệp vụ theo đúng tiến độ kỳ Năm',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-041','2023-KHTH4-Giao KHKD cho các phòng nghiệp vụ theo đúng tiến độ kỳ Quý',3,80.0::numeric,80.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-042','2023-KHTH5-Tham mưu đề xuất GP điều hành thực hiện NVKD - Rà soát, đ/c KHKD của CN gửi TSC',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-043','2023-KHTH6-Tham mưu đề xuất GP điều hành thực hiện NVKD - Rà soát, đ/c KHKD các Phòng tại CN',3,50.0::numeric,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-044','2023-KHTH7-Đầu mối/Thực hiện XD tiêu chí, ban hành văn bản HD xét HTNV tập thể và cá nhân tại CN',3,50.0::numeric,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-045','2023-KHTH8-Thực hiện xét HTNV tập thể và cá nhân kỳ năm',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-046','2023-KHTH9-Thực hiện xét HTNV tập thể và cá nhân kỳ quý',3,80.0::numeric,80.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-047','2023-KHTH10-Đầu mối/ Thực hiện chấm điểm công tác đánh giá HTNV, xếp hạng CN kỳ Năm',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-048','2023-KHTH11-Đầu mối/ Thực hiện công tác đánh giá HTNV, xếp hạng CN kỳ Quý',3,80.0::numeric,80.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-049','2023-KHTH12-Phối hợp trong công tác xếp hạng PGD',3,50.0::numeric,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-050','2023-KHTH13-Báo cáo kết quả HĐKD Chi nhánh hàng ngày',3,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-051','2023-KHTH14-Báo cáo kết quả HĐKD Chi nhánh hàng Tháng',3,30.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-052','2023-KHTH15-Báo cáo kết quả HĐKD Chi nhánh hàng Quý/6 tháng/Năm',3,50.0::numeric,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-053','2023-KHTH16-Báo cáo tình hình hoạt động của các phòng nghiệp vụ hàng tháng',3,50.0::numeric,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-054','2023-KHTH27-Tờ trình BLĐ v/v triển khai các sản phẩm HĐV dân cư; lãi suất HĐV; điều hành vốn',3,20.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-055','2023-KHTH28-Ban hành VB triển khai cập nhật, theo dõi SP HĐVDC; lãi suất HĐV; điều hành vốn',3,20.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-056','2023-KHTH29-Theo dõi, rà soát FTP tiền vay, LS tiền gửi',3,30.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-057','2023-KHTH34-Tính toán, rà soát, đối chiếu cấp bù dự thu dự chi FTP định kỳ/đột xuất',3,50.0::numeric,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-058','2023-KHTH35-Ban hành biểu phí dịch vụ tại Chi nhánh',3,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-059','2023-KHTH36-Đề xuất chính sách phí ưu đãi áp dụng cho KH trình Giám đốc/Hội đồng dịch vụ',3,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-060','2023-KHTH37-Trình, ban hành VB triển khai công tác ĐGCB, HD thực hiện trên PM tại đơn vị',3,50.0::numeric,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-061','2023-KHTH38-Trình ban hành mới Bộ chỉ tiêu BSC phòng, KPIs cán bộ áp dụng tại đơn vị',3,50.0::numeric,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-062','2023-KHTH39-Trình điều chỉnh, cập nhật Bộ chỉ tiêu BSC phòng, KPIs cán bộ áp dụng tại đơn vị',3,30.0::numeric,30.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-063','2023-KHTH40-Thực hiện quy trình ĐGCB trên PS kỳ Quý',3,30.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-064','2023-KHTH41-Thực hiện quy trình ĐGCB trên PS kỳ 6 tháng/năm',3,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-065','2023-KHTH42-Phối hợp rà soát dữ liệu đánh giá cán bộ các vị trí tác nghiệp, TDS...',3,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-066','2023-KHTH43-Tổng hợp nội dung trình phê duyệt kết quả TĐ hàng quý/6 tháng/năm',3,30.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-067','2023-KHTH44-Tổng hợp nội dung Thông báo kết luận họp giao ban/họp chuyên đề',3,20.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-068','2023-KHTH48-Đầu mối/phối hợp với các BP khác của CN triển khai các CV/SP l/quan đến nghiệp vụ KDVTT',3,20.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-069','2023-KHTH53-Công tác tham gia ý kiến - Độ phức tạp rất cao',3,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-070','2023-KHTH54-Công tác tham gia ý kiến - Độ phức tạp cao',3,80.0::numeric,80.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-071','2023-KHTH55-Công tác tham gia ý kiến - Độ phức tạp trung bình',3,50.0::numeric,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-072','2023-KHTH56-Công tác tham gia ý kiến - Độ phức tạp thấp',3,20.0::numeric,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-021','2023-CNTT1-Quản trị, vận hành các ứng dụng phần mềm phân tán cài đặt tại Chi nhánh',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-022','2023-CNTT4-Công tác trực KT, xử lý sự cố hệ thống các máy móc Tbị CNTT và các ctr PMUD tại CN',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-023','2023-CNTT8-Hỗ trợ việc bảo trì định kỳ hàng năm các thiết bị tin học của các phòng.',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-024','2023-CNTT9-Hỗ trợ kỹ thuật từ các phòng ban và giải quyết các sự cố',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-025','2023-CNTT10-Hỗ trợ sử dụng các ứng dụng truy cập từ Internet qua MobiIron',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-026','2023-CNTT11-Phối hợp với Trung tâm CNTT xử lý sự cố hệ thống BDS/TF',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-027','2023-CNTT12-Tổ chức phối hợp chuyển đổi BDS/TF dự phòng định kỳ 2 lần/1 năm',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-028','2023-CNTT15-Phối hợp xử lý sự cố về mạng truyền thông tại Chi nhánh, PGD và ATM',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-029','2023-CNTT19-Quản lý, theo dõi, vận hành CSHT tại CN: Nguồn điện (UPS), camera GS, HT an ninh, VoIP…',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-030','2023-CNTT25-QL HT mạng LAN, kênh truyền nội tình (lắp đặt hub, kéo cáp, bấm cáp..), hệ thống Wifi',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-031','2023-CNTT26-Quản lý các kênh truyền mạng WAN kết nối từ Chi nhánh vể Trung tâm CNTT và các PGD/ATM',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-032','2023-CNTT27-Cải tạo lại hệ thống mạng/điện/điện thoại/camera cho các phòng/PGD',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-033','2023-CNTT38-Qtrị các máy khác p/vụ công việc của riêng CN (máy chủ truyền nhận file, web nội bộ)',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-034','2023-CNTT41-Xây dựng hệ thống mạng/điện/điện thoại/camera phục vụ mở mới PGD',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-035','2023-CNTT42-HD, ĐT, hỗ trợ, kiểm tra GS thực hiện, tuân thủ các quy định và quy trình trong l/v CNTT',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-036','2023-CNTT44-Lập báo cáo và đánh giá ATTT liên qua đến CNTT, báo cáo ISO liên quan đến CNTT',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-037','2023-CNTT48-Khảo sát khách hàng mở kết nối với các đối tác (Thanh toán hóa đơn, Thu hộ…)',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-038','2023-CNTT49-P/h với các đơn vị, BP QL ATM thực hiện cập nhật, bảo trì, khắc phục lỗi các máy ATM',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-039','2023-CNTT51-Kết xuất dữ liệu hỗ trợ nghiệp vụ cho các phòng khi có phát sinh',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-040','2023-CNTT53-P/hợp trong công tác kiểm tra nội bộ nội bộ tại CN và đoàn kiểm tra ngoài, ISO.',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-041','2023-CNTT2-Quản trị hệ thống AD tại Chi nhánh (theo chính sách đã được phê duyệt)',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-042','2023-CNTT3-Quản lý hệ thống thiết bị đầu cuối tại chi nhánh (máy in, máy quét, máy photo...)',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-043','2023-CNTT5-Phối hợp P.TCHC, KHTC trong việc điều chuyển tbị trong và ngoài CN và QLTS về tin học.',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-044','2023-CNTT6-Phối hợp với phòng TCHC, KHTC trong việc xác định thiết bị cần thanh lý.',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-045','2023-CNTT7-Phối hợp với phòng TCHC quản lý việc vào ra cơ quan của thiết bị bảo hành.',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-046','2023-CNTT13-Rà soát virus thủ công (hash file) đối với các Virus đặc biệt nghiêm trọng phát sinh…',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-047','2023-CNTT14-Rà soát HT máy trạm/Internet, cập nhật bản vá hệ điều hành, bản update BIOS…',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-048','2023-CNTT16-Phối hợp TTCNTT các công việc trong triển khai các dự án/PMUD có liên quan khi có y/c',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-049','2023-CNTT17-Lưu trữ, bảo mật, phục hồi dữ liệu Camera và các ctr ư/d và xử lý các sự cố KT tại CN',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-050','2023-CNTT18-Quản trị vận hành hệ thống camera tại ATM',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-051','2023-CNTT20-Cập nhật, kiểm tra t/x công tác phòng chống virus tại các máy trạm thông qua McAffee',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-052','2023-CNTT21-Tổ chức cài đặt, lưu trữ, bảo mật, phục hồi DL, xử lý các sự cố KT và lập HS theo dõi…',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-053','2023-CNTT22-Mua sắm, triển khai hệ thống wifi tại CN',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-054','2023-CNTT23-Vận hành hệ thống kiểm soát kết nối Internet tại Chi nhánh',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-055','2023-CNTT24-Hỗ trợ cho các cán bộ nghiệp vụ và KH sử dụng các dịch vụ có tiện ích/ứng dụng CNTT',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-056','2023-CNTT28-Ktra, đgiá t/tr h/đ tbị CNTT, cập nhật HS, LL của MMTBị CNTT&#59; tham mưu ĐX (nếu có)',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-057','2023-CNTT29-Đầu mối sửa chữa, bảo hành các tbị tin học, đường truyền thông, Internet tại CN, các PGD',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-058','2023-CNTT30-Thực hiện triển khai chính sách ATBM CNTT tới các bộ phận theo hướng dẫn',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-059','2023-CNTT31-Lập báo cáo ATTT liên qua đến CNTT, báo cáo ISO liên quan đến CNTT theo hướng dẫn',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-060','2023-CNTT32-Triển khai thiết bị CNTT PGD số tại CN khi được hỗ trợ trực tiếp từ cấp cao hơn',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-061','2023-CNTT33-Quản trị các thiết bị tại PGD số, quản lý phần mềm triển khai tại PGD số theo hướng dẫn',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-062','2023-CNTT34-Thực hiện mua tbị p/vụ hoạt động tại CN (cung cấp các yêu cầu KT, cấu hình cần mua sắm)',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-063','2023-CNTT35-Cài đặt cấu hình bảng điện tử, màn hình Led hiển thị tỷ giá tại TS CN và các PGD',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-064','2023-CNTT36-Giới thiệu sản phẩm, hướng dẫn sử dụng sản phẩm CNTT cho khách hàng',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-065','2023-CNTT37-Chủ động đề xuất, tham mưu, tổ chức triển khai hoạt động CNTT phục vụ HĐKD đặc thù',5,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-066','2023-CNTT39-Thực hiện các công tác liên quan khác về duy trì, thiết lập hạ tầng phần cứng tại CN',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-067','2023-CNTT40-Quản trị hệ thống kiểm soát kết nối Internet tại Chi nhánh',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-068','2023-CNTT43-Tổ chức triển khai chính sách ATBM CNTT tới các bộ phận',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-069','2023-CNTT45-Triển khai thiết bị CNTT PGD số tại CN',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-070','2023-CNTT46-Quản trị các thiết bị tại PGD số, quản lý phần mềm triển khai tại PGD số',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-071','2023-CNTT47-HD và hỗ trợ KH khi triển khai sản phẩm dịch vụ cho KHDN (Security, iBank, …)',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('CNTT-072','2023-CNTT52-Quản trị và hỗ trợ máy tính kết nối Internet (truyền nhận file với NHNN, đối tác,…)',5,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-062','2023-HCVP36-Thực hiện công tác hậu cần khi lãnh đạo đi công tác(Lo ăn ở, đặt vé máy bay....)',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-063','2023-HCVP37-Lập KH đ/với các khoản chi tiêu hành chính, công tác LTKT, hội nghị, hội thảo.',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-064','2023-HCVP38-Thực hiện các thủ tục tạm ứng và hoàn tạm ứng đúng quy định',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-065','2023-HCVP39-Thực hiện chi tiêu theo quy định - công tác LTKT và chi tiêu HC',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-066','2023-HCVP40-Đầu mối hoặc p/hợp thực hiện công tác hậu cần, t/c hội nghị, hội thảo, công tác lễ tân…',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-067','2023-HCVP41-Phối hợp thực hiện các bảng, biển, decal đảm bảo theo nhận diện thương hiệu…',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-068','2023-HCVP42-Thực hiện các báo cáo theo yêu cầu - công tác LTKT và chi tiêu HC',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-069','2023-HCVP43-Thanh quyết toán các khoản chi tiêu theo quy định',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-070','2023-HCVP44-Lưu hồ sơ theo quy định - công tác LTKT và chi tiêu HC',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-071','2023-HCVP45-Có kế hoạch, PA đảm bảo an ninh, an toàn đ/v người và TS và thực hiện các báo cáo l/q',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-072','2023-HCVP46-P/hợp CQ đ/phương, đối tác về DV an ninh đb an toàn nơi làm việc và công tác v/c TSCG',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-073','2023-HCVP47-Có KH, PA đảm bảo PCCC theo đúng quy định về an toàn PCCC tại TS CN và các PGD.',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-074','2023-HCVP48-Triển khai công tác PCCC tại CN (diễn tập, đ/tạo, truyền thông, quán triệt…tới TT/CN)',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-075','2023-HCVP49-P/hợp các phòng nghiệp vụ, các ĐV c/năng về PCCC đ/bảo HS đầy đủ, đúng QĐ và các BC l/q',2,5.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-076','2023-HCVP50-Có kế hoạch thực hiện công tác Quốc phòng tuân thủ theo quy định của nhà nước.',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-077','2023-HCVP51-Tổ chức t/hiện hoặc p/hợp t/hiện c/tác ANQP, dân quân tự vệ, quân nhân&#59;các BC l/q',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-078','2023-HCVP52-Lưu hồ sơ theo quy định - công tác ANQP, PCCC',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-079','2023-HCVP54-Đ/mối tiếp nhận VB đi/đến (bao gồm cả thư bảo lãnh) và mở sổ TD đ/với các loại VB trên',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-080','2023-HCVP55-T/hiện các thủ tục chuyển phát VB đến đúng nơi QĐ (VPĐT, DV chuyển phát, trình LĐPD...)',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-081','2023-HCVP56-Đ/mối tiếp nhận thư, CPN từ các đơn vị DV và chuyển đến đúng nơi theo y/c',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-082','2023-HCVP58-Tuân thủ việc điều động của lãnh đạo trong việc vận chuyển người và tài sản của đơn vị',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-083','2023-HCVP59-Thực hiện lái xe an toàn trong quá trình vận chuyển (ATGT, an toàn cho người và TS)',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-084','2023-HCVP60-Tuân thủ về QĐ quản lý và sử dụng TS lưu động (tiết kiệm, hiệu quả, đúng mục đích...)',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-085','2023-HCVP61-Thực hiện thanh toán các chi phí liên quan tới công tác vận chuyển',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-086','2023-HCVP62-Lưu hồ sơ theo quy định - công tác vận chuyển',2,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-014','2023-TCNS1-Ban hành TB v/v đề xuất/bổ sung QH cán bộ (các phòng đề xuất có ý kiến của PGĐ PT)',1,5.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-015','2023-TCNS12-Căn cứ định biên SL lãnh đạo và n/cầu bs, rà soát, x/đ n/cầu BN, BNL báo cáo GĐ',1,50.0::numeric,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-016','2023-TCNS13-Dự kiến nhân sự được bổ nhiệm báo cáo Giám đốc',1,30.0::numeric,30.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-017','2023-TCNS14-T/c họp HNLT thông qua chủ trương bs n/cầu nhân sự BN và được BN, n/xét ĐGCB được BN',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-018','2023-TCNS15-Lập biên bản cuộc họp Hội nghị liên tịch ký các thành viên cuộc họp (công tác bổ nhiệm)',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-019','2023-TCNS16-Gửi văn bản xin ý kiến phê duyệt của HO về việc bổ nhiệm cán bộ (nếu có)',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-020','2023-TCNS17-C/bị phiếu đích danh và Lấy phiếu trong Cấp ủy và phòng có CB dự kiến được BN',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-021','2023-TCNS18-Lập Tờ trình báo cáo GĐ về tỷ lệ phiếu, đề xuất bổ nhiệm và ra Quyết định bổ nhiệm',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-022','2023-TCNS19-Công bố quyết định và lưu toàn bộ hồ sơ bổ nhiệm theo quy định',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-023','2023-TCNS20-Cập nhật trên chương trình QLNS (công tác bổ nhiệm)',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-024','2023-TCNS21-Theo dõi, x/đ KH điều động l/c thuộc diện QH, cán bộ thuộc diện l/c đến hạn luân chuyển',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-025','2023-TCNS22-Căn cứ tình hình nhân sự của các phòng, đề xuất điều động luân chuyển đối với cán bộ.',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-026','2023-TCNS23-Lập tờ trình đề xuất với Lãnh đạo về việc điều động, luân chuyển.',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-027','2023-TCNS24-Công bố quyết định và lưu toàn bộ hồ sơ điều động, luân chuyển theo quy định',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-028','2023-TCNS25-Cập nhật trên chương trình QLNS (công tác điều động, luân chuyển)',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-029','2023-TCNS26-Tổ chức Họp hội nghị liên tịch đối với trường hợp điều động cán bộ giữ chức vụ',1,20.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-030','2023-TCNS27-Lập BB cuộc họp HNLT ký các TV cuộc họp đối với trường hợp điều động cán bộ giữ chức vụ',1,10.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-031','2023-TCNS28-Thực hiện tờ trình về việc xây dựng ĐBLĐ của đơn vị trên cơ sở công văn HD của HSC',1,70.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-032','2023-TCNS29-Họp liên tịch Cấp ủy, Ban Giám đốc, BCH Công đoàn thống nhất kế hoạch ĐBLĐ',1,10.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-033','2023-TCNS30-Gửi HS đề nghị PD ĐBLĐ lên HSC trên cơ sở nội dung thống nhất tại cuộc họp liên tịch',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-034','2023-TCNS31-Căn cứ định biên được phê duyệt đăng ký nhu cầu tuyển dụng và có kế hoạch tuyển dụng',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-035','2023-TCNS32-Các thủ tục trước khi thực hiện tuyển dụng (trình KH, PA, hình thức TD, t/lập HĐTD)',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-036','2023-TCNS33-Thông báo tuyển dụng (Báo đài, Website, VPĐT, dán thông báo tại Trụ sở chi nhánh...)',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-037','2023-TCNS34-Tiếp nhận Hồ sơ, chọn lựa ứng viên và trình HĐTD danh sách thí sinh đạt tiêu chí',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-038','2023-TCNS35-Tổ chức thi vòng 2 (thi viết): Chuẩn bị HS, TL, địa điểm thi, tổng hợp đề thi (nếu có).',1,30.0::numeric,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-039','2023-TCNS36-Công bố KQ thi V2: T/hợp KQ, BB và TB nội bộ, p/tiện t/thông và cho TS trúng tuyển.',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-040','2023-TCNS37-Tổ chức thi V3 (phỏng vấn): Chuẩn bị HS, TL, địa điểm thi, tổng hợp đề thi (nếu có).',1,30.0::numeric,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-041','2023-TCNS38-Công bố KQ thi V3: T/hợp KQ, BB và TB nội bộ, p/tiện t/thông và cho TS trúng tuyển.',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-042','2023-TCNS39-Gửi HO kết quả TD, trình GĐ ra QĐ tuyển dụng, ký kết HĐ và xếp lương cho cho CB mới',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-043','2023-TCNS40-Thông báo gặp mặt và phân công cán bộ mới',1,5.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-044','2023-TCNS41-Cập nhật dữ liệu trên chương trình QLNS và lưu hồ sơ tuyển dụng theo quy định',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-045','2023-TCNS42-Công bố DS thí sinh thi tuyển tập trung có nguyện vọng vào làm việc tại CN…',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-046','2023-TCNS43-Lên kế hoạch đào tạo (tháng, quý, năm).',1,30.0::numeric,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-047','2023-TCNS44-Theo dõi cập nhật kịp thời các chương trình đào tạo của Hội sở chính',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-048','2023-TCNS45-T/h các thủ tục cử CB t/gia đ/tạo (TB khóa học, tổng hợp, trình CB t/g, ĐK trên PM...)',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-049','2023-TCNS46-Các thủ tục triển khai đ/tạo (Trình tổ chức khóa học, l/lạc đối tác, TB khóa học...).',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-050','2023-TCNS47-Tổ chức và quản lý lớp học theo đúng quy chế đào tạo của BIDV và của đơn vị.',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-051','2023-TCNS48-Thực hiện thanh toán chi phí và phân bổ chi phí liên quan tới đào tạo.',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-052','2023-TCNS49-Cập nhật chứng chỉ đào tạo trên chương trình QLNS và lưu hồ sơ cán bộ',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-053','2023-TCNS50-Báo cáo, đề xuất về công tác đào tạo (theo khóa học, định kỳ hoặc y/c của lãnh đạo)',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-054','2023-TCNS51-Công tác chấm công (đôn đốc, TD và lưu HS chấm công, NP, nghỉ c/độ BHXH, nghỉ KL…)',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-055','2023-TCNS52-Thu chi lương hàng tháng: bảng kê, truy thu/lĩnh lương, t/h TC lương, các khoản khác…',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-056','2023-TCNS53-C/tác thu chi khác: Chi động viên CB, Chi bs QTN/thêm giờ/truy thu truy lĩnh khác..',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-057','2023-TCNS54-Theo dõi cập nhật LĐBQ, Hs lương bảo hiểm BQ, Lvt BQ, HS lương CN (tháng/quý/năm).',1,20.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-058','2023-TCNS55-Theo dõi và tổng hợp thu nhập của cán bộ hàng tháng phục vụ tính thuế thu nhập cá nhân.',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-059','2023-TCNS56-Theo dõi và thực hiện các thủ tục xếp lương, đ/c lương, nâng bậc lương định kỳ cho CB',1,50.0::numeric,30.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-060','2023-TCNS57-Lập các bcao l/quan tới tiền lương (BC p/h liên phòng, BC BLĐ/TSC, BC LĐ tiền lương...)',1,30.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-061','2023-TCNS58-T/gia vận hành c/tr nhân sự: nhập các dữ liệu l/q đến công tác tiền lương..',1,20.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-062','2023-TCNS59-Theo dõi và khai báo tăng/giảm BH trên Ctr bảo hiểm đ/v CB mới, nghỉ TS, nghỉ ốm đau…',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-063','2023-TCNS60-Thanh toán chế độ BH hàng tháng (trích nộp BH theo QĐ, TT ốm đau, thai sản...)',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-064','2023-TCNS61-Tính tạm ứng và đóng tiền bảo hiểm hàng tháng',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-065','2023-TCNS62-Chốt sổ BH/ Thay đổi thẻ BHYT',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-066','2023-TCNS63-Hướng dẫn cán bộ trong công tác BHXH, BHYT, BHTN',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-067','2023-TCNS64-Thực hiện các báo cáo và lưu hồ sơ',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-068','2023-TCNS65-Cập nhật thay đổi DSCB đóng bảo hiểm BIDV BIC, BIDV Care theo KH hoặc y/c và gửi DS',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-069','2023-TCNS66-Cập nhật thay đổi DS người thân đóng BHBIDV BIC, BIDV Care theo KH hoặc y/c và gửi DS',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-070','2023-TCNS67-Thực hiện thanh toán CP và phân tách chi phí tới các đơn vị (BIC CARE, BIDV CARE,…)',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-071','2023-TCNS68-Hướng dẫn cán bộ trong công tác BH BIC, BH BIDV Care',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-072','2023-TCNS69-Có kế hoạch, thông báo, hướng dẫn công tác thi đua khen thưởng',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-073','2023-TCNS70-P/h với các phòng l/quan trong việc nhận xét, đánh giá ,đề xuất và hoàn thiện HS TĐKT',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-074','2023-TCNS71-Tổ chức họp HĐTĐKT xét duyệt các t/h ĐX, tham mưu DSTĐKT, h/t BBTĐKT với DS được PD',1,20.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-075','2023-TCNS72-Thông báo kết quả Thi đua khen thưởng tới các Cá nhân/đơn vị',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-076','2023-TCNS73-Trực tiếp thực hiện các thủ tục ra QĐ KT hoặc p/h ra QĐ khen thưởng trong TQ của GĐ',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-077','2023-TCNS74-Gửi đề xuất khen thưởng lên HO đối với khen thưởng vượt thẩm quyền của Giám đốc',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-078','2023-TCNS75-Phối hợp với HO hoàn thiện các hồ sơ khen thưởng cho tập thể, cá nhân',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-079','2023-TCNS76-Tiếp nhận và chuyển giao các chứng nhận KT hoặc phối hợp trong công tác tổ chức KT',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-080','2023-TCNS77-Tổng hợp báo cáo công tác TĐKT theo kế hoạch hoặc theo yêu cầu của lãnh đạo',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-081','2023-TCNS78-Tư vấn, đề xuất đảm bảo công tác thi đua khen thưởng được công bằng, hiệu quả.',1,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-082','2023-TCNS79-Lưu hồ sơ khen thưởng theo quy định',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-083','2023-TCNS80-Cập nhật trên chương trình QLNS (công tác TĐKT)',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-084','2023-TCNS81-Hướng dẫn và triển khai các thủ tục ký, tạm hoãn HĐLĐ, nghỉ không lương, Chấm dứt HĐLĐ…',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-085','2023-TCNS82-Theo dõi DS CB đang tạm hoãn HĐLĐ, nghỉ không lương và tiếp nhận cán bộ đi làm trở lại',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-086','2023-TCNS83-Theo dõi và đánh giá năng lực cán bộ',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-087','2023-TCNS84-Rà soát và hoàn tất thủ tục l/q đến c/độ NLĐ khi được điều động đến/đi ĐV khác cùng HT',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-088','2023-TCNS85-P/hợp thực hiện, rà soát, ĐX thay đổi l/q tới MHTC (thành lập, giải thể, thay đổi)',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-089','2023-TCNS86-P/hợp thực hiện, rà soát, ĐX thay đổi liên quan tới chức năng nhiệm vụ các phòng/ban',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-090','2023-TCNS87-Ban hành các quyết định về Mô hình tổ chức, chức năng nhiệm vụ của các phòng ban.',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-091','2023-TCNS88-Cập nhật dữ liệu liên quan đến mô hình tổ chức trên chương trình QLNS',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-092','2023-TCNS89-Tổng hợp sáng kiến cấp CS, tổ chức họp HĐSK, trình cấp có TQ PD và gửi ĐX skiến Cấp KT',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-093','2023-TCNS90-Công tác kỷ luật',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-094','2023-TCNS92-Soạn thảo QĐ thành lập tổ trên cơ sở đề xuất của các phòng',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-095','2023-TCNS93-Có kế hoạch khám sức khỏe cho cán bộ.',1,20.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-096','2023-TCNS94-Các thủ tục khám SK cho cán bộ (trình chủ chương, TB tới CB, HD và tổng hợp y/c,...).',1,50.0::numeric,30.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-097','2023-TCNS95-Thực hiện các thủ tục đấu thầu và chọn lựa đơn vị khám sức khỏe cho cán bộ.',1,30.0::numeric,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-098','2023-TCNS96-Phối hợp đơn vị được chọn tổ chức khám sức khỏe cho cán bộ.',1,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-099','2023-TCNS97-Thanh toán các chi phí liên quan tới khám sức khỏe cho cán bộ',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCNS-100','2023-TCNS98-Tổng hợp báo cáo và đề xuất (sức khỏe)',1,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-073','KHTH Tờ trình - Cập nhật và đề xuất triển khai các quy định của TSC về lãi suất cho vay',3,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('KHTH-074','KHTH Theo dõi FTP tiền vay, LS tiền vay - Cập nhật, triển khai các quy định của TSC về lãi suất cho vay',3,5.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-087','Quản lý xe ô tô được phân giao',2,30.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-088','Bảo quản xe và các giấy tờ xe liên quan đảm bảo không để mất mát, hư hỏng',2,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-089','Định kỳ bảo dưỡng, bảo trì xe ô tô, kiểm tra các thông số kỹ thuật',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-090','Đề xuất biện pháp khắc phục đảm bảo xe luôn sẵn sàng nhận nhiệm vụ',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-091','Đề xuất mua bảo hiểm cho xe ô tô theo quy định',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-092','Đánh số chứng từ và đóng chứng từ của Phòng QLNB',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-093','Hỗ trợ vận chuyển và sắp xếp kho chứng từ',2,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HCVP-094','Đề xuất, khởi tạo thanh toán chi phí xăng xe, chi phí bảo trì, bảo dưỡng đối với xe ô tô đang trực tiếp quản lý',2,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-008','TCKT Xây dựng văn bản chế độ liên quan đến chế độ tài chính, kế toán, phân cấp ủy quyền trong công tác tài chính kế toán tại chi nhánh',4,NULL::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-009','TCKT Thực hiện phân tích, phân bổ chi phí đối với các bộ phận kinh doanh, bộ phận hỗ trợ phục vụ công tác quản trị điều hành',4,10.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-010','TCKT Xây dựng chính sách, theo dõi, quản lý tài sản (giá trị)/vốn và các quỹ, tình hình thực hiện kế hoạch tài chính, định mức chi phí của chi nhánh',4,NULL::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-011','TCKT Thực hiện tổng hợp, kê khai, quyết toán và nộp các loại thuế theo quy định. Quản lý và lập báo cáo tình hình thực hiện nghĩa vụ với NSNN',4,40.0::numeric,40.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-012','TCKT Thẩm định, quản lý, tham gia ý kiến vào các phương án, dự toán mua sắm, chi tiêu',4,8.0::numeric,8.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-013','TCKT Giao dịch hạch toán thu nhập/chi phí từ TKTG theo đề nghị',4,5.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-014','TCKT Giao dịch thẻ, thừa thiếu quỹ tiền mặt, thừa thiếu quỹ ATM',4,4.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-015','TCKT Giao dịch chia sẻ phí',4,4.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-016','TCKT Giao dịch phân bổ bảo lãnh',4,5.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-017','TCKT Giao dịch tiền gửi',4,4.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-018','TCKT Giao dịch XDCB (gồm sửa chữa lớn), quyết toán mua sắm TSCĐ, CCLĐ',4,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-019','TCKT Giao dịch nhập/xuất kho, điều chuyển, thanh lý TS/CCLĐ',4,7.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-020','TCKT Giao dịch sửa chữa TS/CCLĐ, mua bảo hiểm TS/CCLĐ',4,7.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-021','TCKT Giao dịch tăng giảm TS/CCLĐ',4,7.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-022','TCKT Giao dịch nhập/xuất tài sản thuê hoạt động',4,7.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-023','TCKT Giao dịch chi quản lý công vụ chung',4,4.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-024','TCKT Giao dịch Chi NCKH',4,7.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-025','TCKT Giao dịch Chi nhân viên (trừ nộp/chi BHXH)',4,4.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-026','TCKT Giao dịch liên quan đến quỹ thu nhập',4,7.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-027','TCKT Nộp/chi bảo hiểm xã hội',4,4.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-028','TCKT Giao dịch ấn chỉ, vật liệu',4,4.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-029','TCKT Giao dịch chi Lễ tân khánh tiết',4,5.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-030','TCKT Giao dịch chi tiếp thị, khuyến mại, hội nghị, hội thảo',4,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-031','TCKT Giao dịch chi HHMG',4,10.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-032','TCKT Giao dịch nộp thuế',4,9.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-033','TCKT Giao dịch khác có độ phức tạp cao',4,7.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-034','TCKT Giao dịch khác có độ phức tạp trung bình',4,4.0::numeric,3.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-035','TCKT Giao dịch khác có độ phức tạp thấp',4,1.0::numeric,1.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-036','TCKT 1.1 Kiểm soát Cân đối TKKT ngày',4,10.0::numeric,8.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-037','TCKT 1.2 Kiểm soát Cân đối TKKT tháng',4,7.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-038','TCKT 1.3 Kiểm soát Cân đối TKKT năm',4,4.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-039','TCKT 2 Kiểm soát TK trung gian',4,7.0::numeric,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-040','TCKT 3 Kiểm tra, đối chiếu số dư tài khoản TGTT với các TCTD khác (một số chi nhánh)',4,4.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-041','TCKT 4.1 Kiểm soát  các báo cáo Kế toán tổng hợp',4,7.0::numeric,7.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-042','TCKT 4.2 Rà soát các biến động bất thường, nghi ngờ,... theo hướng dẫn tại từng thời kỳ của BIDV',4,7.0::numeric,7.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-043','TCKT 4.3. Phối hợp với các phòng ban tại CN thực hiện điều chỉnh GL khi có yêu cầu',4,4.0::numeric,2.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-044','TCKT 4.4. Kiểm soát công nợ phải thu, phải trả, theo dõi, quản lý và tổng hợp, báo cáo hàng kỳ đối với toàn bộ khoản công nợ trên chương trình quản lý công nợ',4,NULL::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-045','TCKT 4.5 Kiểm soát số liệu kế toán khác (dự thu, dự chi, thu nhập chờ phân bổ, chi phí chờ phân bổ, các khoản mục ngoại bảng…)',4,5.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-046','TCKT 5.Kiểm soát báo cáo khác',4,4.0::numeric,4.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-047','TCKT  Công tác tập hợp,lưu trữ chứng từ hàng ngày',4,8.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-048','TCKT  Công tác lưu trữ tài liệu, chứng từ kế toán chi nhánh',4,9.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-049','TCKT  Lập các loại báo cáo kế toán tài chính theo quy định của Nhà nước và cung cấp số liệu kế toán phục vụ công tác quản trị điều hành của chi nhánh',4,70.0::numeric,70.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-050','TCKT Cung cấp/Giải trình tài liệu, số liệu kế toán phục vụ công tác thanh tra, kiểm tra, kiểm toán…. Độ phức tạp rất cao',4,100.0::numeric,100.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-051','TCKT Cung cấp/Giải trình tài liệu, số liệu kế toán phục vụ công tác thanh tra, kiểm tra, kiểm toán….Độ phức tạp cao',4,70.0::numeric,70.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-052','TCKT Cung cấp/Giải trình tài liệu, số liệu kế toán phục vụ công tác thanh tra, kiểm tra, kiểm toán….Độ phức tạp trung bình',4,40.0::numeric,40.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-053','TCKT Cung cấp/Giải trình tài liệu, số liệu kế toán phục vụ công tác thanh tra, kiểm tra, kiểm toán….Độ phức tạp thấp',4,10.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-054','TCKT  Lập/ Kiểm soát báo cáo quyết toán năm',4,10.0::numeric,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-055','TCKT  Triển khai công tác quyết toán hàng năm',4,82.0::numeric,82.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-056','TCKT  Triển khai các chương trình phần mềm TCKT theo hướng dẫn của TSC',4,40.0::numeric,30.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TCKT-057','TCKT  Triển khai các văn bản, chế độ, quy định về TCKT tại đơn vị',4,50.0::numeric,80.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TAPVU-001','TAPVU Tuân thủ các quy định của Chi nhánh về an ninh, an toàn và bảo mật thông tin; không tự ý tiếp cận, di chuyển, xem hoặc xử lý hồ sơ, chứng từ, tài sản, trang thiết bị và các khu vực hạn chế; kịp thời báo cáo khi phát hiện các dấu hiệu bất thường hoặc nguy cơ mất an toàn, bảo mật.',6,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TAPVU-002','TAPVU Vệ sinh, sắp xếp bàn ghế; chuẩn bị nước uống, cốc/chén; kiểm tra phòng trước và thu dọn sau cuộc họp',6,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TAPVU-003','TAPVU Vệ sinh phòng làm việc Ban giám đốc; chuẩn bị nước uống và bảo đảm không gian sạch sẽ, ngăn nắp',6,30.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TAPVU-004','TAPVU Theo dõi giấy vệ sinh, nước rửa tay, túi rác, hóa chất, dụng cụ vệ sinh; báo cáo nhu cầu bổ sung kịp thời',6,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TAPVU-005','TAPVU Chuẩn bị trà, nước phục vụ Ban Giám đốc, khách và các cuộc họp/hội nghị theo yêu cầu',6,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('TAPVU-006','TAPVU Thực hiện các công việc phục vụ, vệ sinh khác theo phân công phù hợp với chức năng, nhiệm vụ',6,10.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-001','DANG Tham mưu chương trình, kế hoạch công tác; chuẩn bị nội dung phục vụ Đảng ủy, Ban Thường vụ, các Chi bộ',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-002','DANG Tiếp nhận, trình, phát hành và theo dõi văn bản đến/đi; soạn thảo thông báo, nghị quyết, báo cáo, chương trình công tác',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-003','DANG Chuẩn bị tài liệu, chương trình, giấy mời; tổng hợp nội dung; hoàn thiện biên bản, nghị quyết/kết luận và theo dõi thực hiện sau họp',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-004','DANG Theo dõi danh sách, hồ sơ, thông tin đảng viên; chuyển sinh hoạt Đảng; cập nhật biến động và thực hiện các thủ tục liên quan',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-005','DANG Theo dõi nguồn phát triển Đảng; hồ sơ quần chúng ưu tú; kết nạp Đảng; quản lý đảng viên dự bị; công nhận đảng viên chính thức',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-006','DANG Theo dõi, đăng ký lớp nhận thức về Đảng, lớp đảng viên mới, bồi dưỡng lý luận chính trị và nghiệp vụ công tác Đảng',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-007','DANG Theo dõi chương trình kiểm tra, giám sát; chuẩn bị hồ sơ, tài liệu và tổng hợp kết quả thực hiện',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-008','DANG Thực hiện kiểm điểm, đánh giá, xếp loại tổ chức Đảng và đảng',7,20.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-009','DANG Tổng hợp thành tích; lập hồ sơ đề nghị khen thưởng tổ chức Đảng, đảng viên; theo dõi kết quả khen thưởng',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-010','DANG Sắp xếp, lưu trữ hồ sơ đảng viên, nghị quyết, biên bản, báo cáo và tài liệu công tác Đảng; bảo đảm bảo mật',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-011','DANG Tổng hợp báo cáo định kỳ, chuyên đề, đột xuất; theo dõi và đôn đốc các Chi bộ thực hiện chế độ báo cáo',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-012','DANG Theo dõi chương trình công tác, nhiệm vụ được giao; đôn đốc các Chi bộ/đơn vị và tổng hợp tiến độ, kết quả thực hiệ',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-013','DANG Phối hợp tổ chức đại hội, hội nghị, lễ kết nạp, trao Huy hiệu Đảng, chương trình về nguồn và các hoạt động chính trị',7,50.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-014','DANG Cập nhật dữ liệu, hồ sơ và thực hiện các nghiệp vụ trên các hệ thống/phần mềm công tác Đảng theo quy định',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-015','DANG Thực hiện các nhiệm vụ phát sinh theo chỉ đạo của Đảng ủy, Bí thư/Phó Bí thư và yêu cầu của Đảng ủy cấp trên',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-016','DANG Theo dõi danh sách đảng viên, mức đóng và số đảng phí phải thu của từng đảng viên theo quy định',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-017','DANG Thông báo, hướng dẫn, đôn đốc đảng viên thực hiện nộp đảng phí đầy đủ, đúng thời hạn',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-018','DANG Theo dõi, cập nhật và đối chiếu tình trạng nộp đảng phí của đảng viên trên hệ thống/ứng dụng được triển khai',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-019','DANG Đối chiếu số phải thu, thực thu, số đã nộp và số còn phải thu; xử lý hoặc báo cáo các trường hợp chênh lệch',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-020','DANG Xác định số đảng phí được để lại và số phải nộp cấp trên; thực hiện thủ tục nộp theo quy định',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-021','DANG Theo dõi các khoản thu, chi từ nguồn tài chính của Chi bộ; bảo đảm chi đúng nội dung, thẩm quyền và nguồn kinh phí',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-022','DANG Kiểm tra hồ sơ, chứng từ; thực hiện thanh toán các khoản chi phục vụ hoạt động của Chi bộ sau khi được phê duyệt',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-023','DANG Theo dõi số dư tiền, kinh phí được để lại và tình hình sử dụng nguồn tài chính của Chi bộ',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-024','DANG Cập nhật sổ thu – chi, sổ theo dõi đảng phí và các bảng đối chiếu liên quan theo quy định',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-025','DANG Thu thập, kiểm tra, sắp xếp và lưu trữ chứng từ thu – chi, chứng từ nộp đảng phí và các hồ sơ tài chính liên quan',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-026','DANG Chuẩn bị số liệu phục vụ báo cáo, công khai tình hình thu – chi và sử dụng đảng phí trước Chi ủy/Chi bộ theo quy định',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-027','DANG Tổng hợp số liệu, lập báo cáo/quyết toán tài chính Chi bộ cuối kỳ, cuối năm hoặc theo yêu cầu',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-028','DANG Chuẩn bị sổ sách, chứng từ, bảng kê và số liệu phục vụ công tác kiểm tra tài chính Đảng',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-029','DANG Phối hợp cập nhật tăng, giảm, chuyển sinh hoạt Đảng để điều chỉnh danh sách và nghĩa vụ đóng đảng phí',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-030','DANG Cung cấp số liệu và thực hiện các nhiệm vụ tài chính, đảng phí khác theo phân công của Bí thư/Chi ủy',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-031','CONGDOAN Theo dõi, hạch toán các khoản thu kinh phí, đoàn phí; đối chiếu số phải thu, đã thu và số phải nộp cấp trên',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-032','CONGDOAN Tiếp nhận, kiểm tra hồ sơ thanh toán; thực hiện chi đúng đối tượng, nội dung, định mức và nguồn kinh phí',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-033','CONGDOAN Kiểm tra tính đầy đủ, hợp lệ của chứng từ; sắp xếp, lưu trữ hồ sơ thu, chi, thanh toán theo quy định',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-034','CONGDOAN Phối hợp xây dựng dự toán thu – chi hằng năm; theo dõi tình hình thực hiện và đề xuất điều chỉnh khi cần thiết',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-035','CONGDOAN Theo dõi kinh phí theo từng nguồn, nội dung và chương trình; kiểm soát mức sử dụng so với dự toán được duyệt',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-036','CONGDOAN Tổng hợp số liệu, lập báo cáo quyết toán định kỳ/năm; đối chiếu số liệu trước khi trình phê duyệt và gửi Công đoàn cấp trên',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-037','CONGDOAN Lập các báo cáo thu – chi, tồn quỹ, tình hình sử dụng kinh phí và các báo cáo định kỳ/đột xuất theo yêu cầu',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-038','CONGDOAN Thực hiện thủ tục tài chính cho các chương trình thăm hỏi, phúc lợi, hiếu hỷ, nghỉ mát, văn hóa – thể thao, nữ công, an sinh xã hội và các hoạt động khác',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-039','CONGDOAN Chuẩn bị số liệu phục vụ công khai tài chính; cung cấp số liệu cho Ban Chấp hành, Ban Thường vụ và các bộ phận có liên quan',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric),
  ('HDDT-040','CONGDOAN Cập nhật quy định; cung cấp số liệu, hồ sơ và thực hiện các nhiệm vụ tài chính – kế toán khác theo phân công của BCH/Ban Thường vụ Công đoàn',7,5.0::numeric,NULL::numeric,NULL::numeric,NULL::numeric,NULL::numeric)
) as v(ma_cv, ten_cong_viec, ma_mang, diem_can_bo, diem_kiem_soat, diem_truong_phong, diem_pgd, diem_gd)
join mang_cv m on m.ma_mang = v.ma_mang
on conflict (ma_cv) do nothing;
